name: build and push image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1.3.0
      - uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2.4.0
        with:
          context: ./general/base
          file: ./general/base/Dockerfile
          push: true
          tags: ghcr.io/fancl20/workspace:general-base
      - uses: docker/build-push-action@v2.4.0
        with:
          context: ./general/common
          file: ./general/common/Dockerfile
          push: true
          tags: ghcr.io/fancl20/workspace:general-common
