name: build and push image

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: ./general/base
          file: ./general/base/Dockerfile
          push: true
          tags: fancl20/workspace:general-base
      - uses: docker/build-push-action@v2
        with:
          context: ./general/golang
          file: ./general/golang/Dockerfile
          push: true
          tags: fancl20/workspace:general-golang
      - uses: docker/build-push-action@v2
        with:
          context: ./project/bodman
          file: ./project/bodman/Dockerfile
          push: true
          tags: fancl20/workspace:project-bodman
